### ISSUE TITLE
Could not deduce MonadSqlQuery for TransactionM

### ISSUE THREAD

**Issue by qwbarch** [brandonchinn178/persistent-mtl#43]
I'm following the README, where I have this schema:
```haskell
share [mkPersist sqlSettings, mkMigrate "migrate"] [persistLowerCase|
Person
  name String
  age Int
  deriving Show Eq
|]
```
And then I attempt to "insert" a ``Person`` within a transaction:
```haskell
foo :: MonadSqlQuery m => m ()
foo = withTransaction $ do
  insert_ @Person undefined
```
Which ends up with the following error message:
```haskell
[typecheck -Wdeferred-type-errors] [E] • Could not deduce (MonadSqlQuery                              
+                            (Database.Persist.Monad.Class.TransactionM m))                                  
+          arising from a use of ‘foo’                                                                 
+        from the context: MonadSqlQuery m 
```
How do I use functions from the ``shim`` module within a transaction?

**Comment by qwbarch** [comment]
This also doesn't compile for me:
```haskell
let env = mkSqlQueryEnv pool $ \env -> env
        { retryIf = isSerializationError . fromException
        , retryLimit = 100 -- defaults to 10
        }
```
``isSerializationError`` expects an ``SqlError``, whereas ``fromException`` returns a ``Maybe``. Is the README out of date?
Embarrassingly enough, I don't even know how to cast the ``SomeException`` to a ``SqlError`` so that it aligns with ``isSerializationError``.
Could you drop another example on that as well? Thanks in advance!

**Comment by brandonchinn178** [comment]
ah seems like the `withTransaction` part of the README was written before `TransactionM` was a thing. A quick fix for that would be to add `MonadSqlQuery (TransactionM m)` as a constraint, but let me look into making the UX better there.

And seems like the `retryIf` example is slightly off. It should be `maybe False isSerializationError`. (`fromException` takes a `SomeException` and returns `Just` with the correct error type, or `Nothing` if the `SomeException` had a different error type)

**Comment by brandonchinn178** [comment]
Fixes here: https://github.com/brandonchinn178/persistent-mtl/pull/44

**Comment by qwbarch** [comment]
That was an incredibly quick fix. Looking forward to the PR being merged!
Thanks for the help, and for creating the library. I'm really enjoying it so far
