### ISSUE TITLE
Doesn't accept unliftio-pool-0.4 or resourcet-1.3

### ISSUE THREAD

**Issue by ysangkok** [brandonchinn178/persistent-mtl#64]
cabal outdated reports:

```
Outdated dependencies:
mtl >=2.2.2 && <2.3 (latest: 2.3.1)
resourcet >=1.2.4 && <1.3 (latest: 1.3.0)
transformers >=0.5.6 && <0.6 (latest: 0.6.1.0)
unliftio-pool >=0.2 && <0.3 (latest: 0.4.1.0)
```

See also commercialhaskell/stackage/issues/6744

**Comment by brandonchinn178** [comment]
That doesnt make sense. I updated persistent-mtl for unliftio-pool 0.4

https://github.com/commercialhaskell/stackage/issues/6852

**Comment by ysangkok** [comment]
Oh, I see, it's just because I ran it on the repo, and not on the revised cabal file. Never mind, sorry!

**Comment by brandonchinn178** [comment]
Yeah, I haven't updated the repo yet. Will get around to it at some point
